# Generated by Django 5.1.6 on 2025-03-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=64)),
                ('bio', models.CharField(max_length=512)),
                ('interests', models.JSONField()),
                ('skills', models.JSONField()),
                ('user_type', models.CharField(choices=[('1', 'Producer'), ('2', 'Musician'), ('3', 'Singer')], max_length=8)),
            ],
        ),
    ]
