# Generated by Django 5.1.6 on 2025-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='1234', max_length=64),
            preserve_default=False,
        ),
    ]
