# Generated by Django 5.1.7 on 2025-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
