# Generated by Django 5.1.7 on 2025-04-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_password_alter_customuser_username'),
        ('users', '0009_customuser_genres'),
    ]

    operations = [
    ]
