# Generated by Django 5.1.7 on 2025-04-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('file', models.FileField(upload_to='song_uploads/')),
            ],
        ),
    ]
