# Generated by Django 5.1.7 on 2025-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedsong',
            name='file',
            field=models.FileField(null=True, upload_to='song_uploads/'),
        ),
    ]
