# Generated by Django 5.1.7 on 2025-04-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_uploadedsong_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
    ]
