# Generated by Django 5.1.7 on 2025-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_songcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcomment',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
