# Generated by Django 5.1.7 on 2025-04-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedsong',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='uploadedsong',
            name='file',
            field=models.FileField(upload_to='song_uploads/'),
        ),
    ]
