# Generated by Django 5.1.7 on 2025-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='image_uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='song',
            field=models.FileField(null=True, upload_to='song_uploads/'),
        ),
    ]
