# Generated by Django 5.1.7 on 2025-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_image_post_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
